spring:
  autoconfigure:
    # Spring Boot? ?? ?? ???
    # SecurityAutoConfiguration(?? ?? ??)? ??
    # ? ??? ??, ?? ?? ?? ?? ?? ?? ????
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  application:
    # ?????? ??
    # ??, Actuator, ??????? ???? ???? ???
    name: spring-bean-practice

  jackson:
    serialization:
      # JSON ??? ? ?? ??? ?? ?? ???? ??
      # ObjectMapper? INDENT_OUTPUT ??? ??
      indent-output: true

my:
  # ??? ?? ???? ??
  # @Value(\"${my.greeting}\") ??? ?? ??
  greeting: "Hello, Codeit Spring Bootcamp!"
  boolean: false
  number: 1234

server:
  # ?? ?? ?? ?? ??
  port: 8080
